name: tabbar_app
description: "Aplicativo Flutter com TabBar e persistência de dados em sqflite 
(plugin do SQLite para Flutter). "
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:

assets:
  - /assets/profile_icon.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
